[pytest]
addopts = --device==device_01 --allure-epics=Router --allure-features=Device -p no:warnings

; ===== 用例发现 =====
testpaths = testcases
python_files = test_01*.py
python_classes = Test*
python_functions = test_*

; ===== markers =====
markers =
    smoke: 冒烟用例
    high: 高优先级
    middle: 中优先级
    low: 低优先级

; ===== 中文 =====
console_output_style = classic

; ===== 警告 =====
filterwarnings =
    ignore::DeprecationWarning
    ignore::ResourceWarning

; ===== 设备选择 =====
; 可选值: all, device_01, device_02
; 默认: all
device_filter = all