# config/app_config.yaml
appium:
#  server: "http://127.0.0.1:4723"
  server: "http://host.docker.internal:4723"

# 设备配置（通用，不限制设备名称）
devices:
  device_01:
    udid: "619aae4"
    system_port: 8200
    enabled: true

  device_02:
    udid: "emulator-5554"
    system_port: 8201
    enabled: true

# =======================
# 并发配置
# =======================
parallel:
  enabled: false          # 是否开启多设备并发执行（true/false）
  devices: 2              # 并发设备数量（当 enabled 为 true 时生效）
  device_filter: "all"    # 设备过滤器（all/device_01/device_02等）